
    drop table if exists T_SYS_USER;
    drop table if exists T_SYS_ROLE;
    drop table if exists T_SYS_U2R;
    drop table if exists T_SYS_PERMSSION;
    drop table if exists T_SYS_MENU;
    drop table if exists T_SYS_R2P;
    drop table if exists T_BLOG;

    create table T_SYS_USER (
        ID bigint generated by default as identity,
        EMAIL varchar(255),
        LOGIN_NAME varchar(255) not null unique,
        NAME varchar(255),
        PASSWORD varchar(255),
        OTHER varchar(512),
        primary key (ID)
    ) ;
     create table T_SYS_ROLE (
        ID bigint generated by default as identity,
        ROLE_NAME varchar(255) not null unique,
        primary key (ID)
    ) ;
	create table T_SYS_U2R (
        USER_ID bigint not null,
        ROLE_ID bigint not null,
     	primary key(USER_ID,ROLE_ID),
        foreign key(USER_ID) references T_SYS_USER(ID),
        foreign key(ROLE_ID) references T_SYS_ROLE(ID)
    ) ;
    
     create table T_SYS_MENU (
        ID bigint generated by default as identity,
        PARENT_ID bigint,
        MENU_NAME varchar(50),
        ALIAS_NAME varchar(50),
        MENU_URL varchar(512),
        MENU_TYPE varchar(50),
        ORDER_NUM int,
        primary key (id)
    ) ;
   
    create table T_SYS_PERMSSION (
        ID bigint generated by default as identity,
        ROLE_ID bigint,
        MENU_ID bigint,
        RES_NAME varchar(50),
        RES_CN_NAME varchar(50),
        OPERATION varchar(50),
        primary key (id)
    ) ;
    create table T_SYS_R2P (
        role_id bigint not null,
        perm_id bigint not null,
        foreign key(role_id) references T_SYS_ROLE(ID),
        foreign key(perm_id) references T_SYS_PERMSSION(ID)
    ) ;
    
    create table T_BLOG (
        ID bigint generated by default as identity,
        TITLE varchar(255) not null,
        AUTHOR varchar(20),
        CATEGORY varchar(50),
        URL varchar(512),
        OTHER varchar(1024),
        CREATER varchar(20),
        PUBLISH_DATE date,
        primary key (id)
    ) ;
